In [59]:
import numpy as np
"""
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), 
all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.
the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.
e.g 
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the 
same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less 
functionality. The more important attributes of an ndarray object are:
"""
a = np.arange(15).reshape(3,5)#arange an array of 15 random numbers. Reshape (row,column)
print(a)
print(a.shape) #returns shape of the ndarray , (row,column).
print(a.ndim) # n dimentions. 
print(a.dtype.name) # data type of the elements of the array.
print(a.itemsize) #the size in bytes of each element of the array.
print(a.data) #the buffer containing the actual elements of the array ADDRESS in memory.
print(a.size) #number of elements of row * column.
print(type(a))
b = np.array([5,6,7])
type(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int64
8
15
<class 'numpy.ndarray'>


numpy.ndarray

In [60]:
import numpy as np
#Array Creation
"""
For example, you can create an array from a regular Python list or tuple using the array function. 
The type of the resulting array is deduced from the type of the elements in the sequences.
"""
a = np.array([2,3,4])
a.dtype
b = np.array([1.2,3.5,5.1])
b.dtype
"""
array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of 
sequences into three-dimensional arrays, and so on
"""
b =  np.array([[1.4,2,5],[5,6,7], [1,2,3]])
b.dtype
print(b)
#The type of the array can also be explicitly specified at creation time:
c = np.array([[1,2],[3,4]], dtype = complex)
c
"""
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists
-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must 
specify 'dtype=object' when creating the ndarray
"""
b = np.array([[7,8],[[1,2],[3,4],[5,6]]],dtype = object)
print(b)
print("\n")
#3D array "here
a = np.array([[[1,2,3],[1,2,3],[1,2,3],[1,2,3]]])
print(a)

print(a.shape) #returns shape of the ndarray , (...depth,row,column).
print(a.ndim) # n dimentions. 
print(a.dtype.name) # data type of the elements of the array.
print(a.itemsize) #the size in bytes of each element of the array.
print(a.data) #the buffer containing the actual elements of the array ADDRESS in memory.
print(a.size) #number of elements of row * column.
print(type(a))

[[1.4 2.  5. ]
 [5.  6.  7. ]
 [1.  2.  3. ]]
[list([7, 8]) list([[1, 2], [3, 4], [5, 6]])]


[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]
(1, 4, 3)
3
int64
8
12
<class 'numpy.ndarray'>


In [61]:
import numpy as np
from numpy import pi
"""
Often, the elements of an array are originally unknown,
but its size is known. Hence, NumPy offers several 
functions to create arrays with initial placeholder 
content. These minimize the necessity of growing 
arrays, an expensive operation.

The function zeros creates an array full of zeros, 
the function ones creates an array full of ones, and 
the function empty creates an array whose initial content is random and 
depends on the state of the memory. 
By default, the dtype of the created array is float64.
"""
a = np.zeros((3, 4))#2D , rows(y), columns(x)
#print(a)
b = np.ones((2,3,4), dtype=np.int16)#3D depth(z), row(y), column(x)
print(b)
print("\n")
b_1 = np.ones((3,2,3,4), dtype=np.int16)
#print(b_1)
c = np.empty((2,3))# uninitialized
print(c)#2D

"""
To create sequences of numbers, NumPy provides 
the arange function which is analogous to the 
Python built-in range, but returns an array.
"""
np.arange(10,30,5)#start , stop , step
np.arange(0, 2 ,0.3)# it accepts float arguments
"""
When arange is used with floating point arguments, it is generally not 
possible to predict the number of elements obtained, due to the finite 
floating point precision. For this reason, it is usually better to use 
the function linspace that receives as an argument the number of elements 
that we want, instead of the step.
"""
np.linspace(0,2,9)# 9 numbers from 0 to 2
x = np.linspace(0, 2*pi, 100)#useful to evaluate function at lots of points
print(type(x))
f = np.sin(x)
print(type(f))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


[[  0. 100. 200.]
 [300. 400. 500.]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [62]:
#Printing arrays
"""
When you print an array, NumPy displays it in a similar way to nested 
lists, but with the following layout:

1. The last axis is printed from left to right,

2. The second-to-last is printed from top to bottom,

3. The rest are also printed from top to bottom, with each slice separated 
from the next by an empty line.
"""
#One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
a = np.arange(6) #1D array as list
print(a)
print()
b = np.arange(12).reshape(4,3) #2D array as matrices
print(b)
print()

c = np.arange(24).reshape(2,4,3) #3D array as list of matrices
print(c)
print()

d = np.arange(48).reshape(2,2,4,3) #4D or more as list of list of matrices
print(d)

[0 1 2 3 4 5]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]

[[[[ 0  1  2]
   [ 3  4  5]
   [ 6  7  8]
   [ 9 10 11]]

  [[12 13 14]
   [15 16 17]
   [18 19 20]
   [21 22 23]]]


 [[[24 25 26]
   [27 28 29]
   [30 31 32]
   [33 34 35]]

  [[36 37 38]
   [39 40 41]
   [42 43 44]
   [45 46 47]]]]


In [63]:
"""
If an array is too large to be printed, NumPy automatically skips the central part of 
the array and only prints the corners:
"""
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))
#print(np.arange(1000000).reshape(100,100,100))
"""
To disable this behaviour and force NumPy to print the entire array, you can change the printing 
options using set_printoptions.
"""
import sys
#np.set_printoptions(threshold=sys.maxsize)

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [64]:
#array returns a list as ndarray
a = np.array([20,30,40,50])
print(a)
#arange returns an nd array of parameter size
b = np.arange(4)
print(b)

subT = a-b
print(subT)
ADDT = a+b
print(ADDT)
poweR = a**2
print(poweR)
TrigRatios = (10*np.sin(a))/(10*np.cos(a))
print(TrigRatios)
tan_a = np.tan(a)
print(tan_a)

a<34

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[20 31 42 53]
[ 400  900 1600 2500]
[ 2.23716094 -6.4053312  -1.11721493 -0.27190061]
[ 2.23716094 -6.4053312  -1.11721493 -0.27190061]


array([ True,  True, False, False])

In [65]:
"""
MATRIX CALCULATION

Unlike in many matrix languages, the product operator * operates elementwise in NumPy
arrays. The matrix product can be performed using the @ operator (in python >=3.5) or 
the dot function or method:
"""

a = np.array([ [1,1],
               [0,1] ])
b = np.array([ [2,0],
               [3,4] ])
Element_wise_multiplication = a * b
print(Element_wise_multiplication)
Matrix_product = a @ b
print(Matrix_product)
Matrix_dot_product = a.dot(b)
print(Matrix_dot_product)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [66]:
"""
Some operations, such as += and *=, act in place to modify an existing
array rather than create a new one.
"""
#Create instance of default random number generator
random_generator = np.random.default_rng(1)
print(random_generator)
print(type(random_generator))
a = np.ones((2,3), dtype=np.int32)
print(a)
print(type(a))
print(a.dtype)
b = random_generator.random((2,3))
print(b)
print(type(b))
print(b.dtype)

print("{},{}".format(a.shape,a.ndim)) #Format()
print(f"{b.shape}, {b.ndim}")#F String

#Assignment operators:
a *= 3
b += a 
print(a)
print(b)
print(f"{b + a}")

Generator(PCG64)
<class 'numpy.random._generator.Generator'>
[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int32
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
<class 'numpy.ndarray'>
float64
(2, 3),2
(2, 3), 2
[[3 3 3]
 [3 3 3]]
[[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]
[[6.51182162 6.9504637  6.14415961]
 [6.94864945 6.31183145 6.42332645]]


In [67]:
#UPCASTING
"""
When operating with arrays of different types, the type of 
the resulting array corresponds to the more
general or precise one (a behavior known as upcasting).
"""
import math
a = np.ones(3, dtype=np.int32) #column, dtype
b = np.linspace(0, math.pi ,3)
print(f"{type(a)} {type(b)}")
print(b.dtype.name)

c = a+b

d = c * 1j
print()
print(c)
print()
print(d)
print()
print(f"{type(c)} {c.dtype.name}")
print(f"{type(d)} {d.dtype.name}")

#An array with exponential of all elements of input array.
#numpy.exp(array, out = None, where = True, casting = ‘same_kind’, order = ‘K’, dtype = None) :

d = np.exp(d)
print(d)

<class 'numpy.ndarray'> <class 'numpy.ndarray'>
float64

[1.         2.57079633 4.14159265]

[0.+1.j         0.+2.57079633j 0.+4.14159265j]

<class 'numpy.ndarray'> float64
<class 'numpy.ndarray'> complex128
[ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]


In [68]:
"""
Many unary operations, such as computing the sum of all the elements 
in the array, are implemented as methods of the ndarray class.
"""
a = random_generator.random((2,3))
print(f"{a} \n{type(a)} {a.dtype.name}")

#SUM
print(a.sum())

#MIN
print(a.min())

#MAX
print(a.max())


"""
By default, these operations apply to the array as though it were a list of numbers, regardless of its 
shape. However, by specifying the axis parameter you can apply an operation along the specified axis 
of an array:
"""
b =np.arange(12).reshape(3,4)
print(b)
print()

#SUM,MIN,MAX... ALONG COLUMN
print(b.sum(axis=0))
print(f"{b.min(axis=0)} {b.max(axis=0)}")
print()

#SUM,MIN,MAX.... ALONG ROW
print(b.sum(axis=1))
print(f"{b.min(axis=1)} {b.max(axis=1)}")
print()

#CUMULATIVE SUM ALONG MENTIONED AXIS
print(b.cumsum(axis=1))
print()
print(b.cumsum(axis=0))

[[0.82770259 0.40919914 0.54959369]
 [0.02755911 0.75351311 0.53814331]] 
<class 'numpy.ndarray'> float64
3.1057109529998157
0.027559113243068367
0.8277025938204418
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[12 15 18 21]
[0 1 2 3] [ 8  9 10 11]

[ 6 22 38]
[0 4 8] [ 3  7 11]

[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]

[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]


In [69]:
#UNIVERSAL FUNCTIONS ->
"""
NumPy provides familiar mathematical functions such as sin, cos, and exp.
In NumPy, these are called “universal functions”(ufunc). Within NumPy, these 
functions operate elementwise on an array, producing an array as output.
"""
b = np.arange(3)
c = np.array([1,-4,8])
print(b)
print()
print(f"{np.exp(b)} \n{np.sqrt(b)} \n{np.add(b,c)}")

"""
OTHER UFUNCS INCLUDE :

all, any, apply_along_axis, argmax, argmin, argsort, 
average, bincount, ceil, clip, conj, corrcoef, cov, 
cross, cumprod, cumsum, diff, dot, floor, inner, 
invert, lexsort, max, maximum, mean, median, min, 
minimum, nonzero, outer, prod, re, round, sort, std, 
sum, trace, transpose, var, vdot, vectorize, where

https://numpy.org/devdocs/user/quickstart.html#quickstart-shape-manipulation
"""

[0 1 2]

[1.         2.71828183 7.3890561 ] 
[0.         1.         1.41421356] 
[ 1 -3 10]


'\nOTHER UFUNCS INCLUDE :\n\nall, any, apply_along_axis, argmax, argmin, argsort, \naverage, bincount, ceil, clip, conj, corrcoef, cov, \ncross, cumprod, cumsum, diff, dot, floor, inner, \ninvert, lexsort, max, maximum, mean, median, min, \nminimum, nonzero, outer, prod, re, round, sort, std, \nsum, trace, transpose, var, vdot, vectorize, where\n\nhttps://numpy.org/devdocs/user/quickstart.html#quickstart-shape-manipulation\n'

In [70]:
"""
Indexing, Slicing and Iterating
One-dimensional arrays can be indexed, sliced and iterated over, much like 
lists and other Python sequences.
"""
a = np.arange(10)**3
print(a)
print(a[2])
print(a[2:5])
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
print(a)
print(a[ : :-1])#Reversed
for i in a:
    print(i**(1/3.))

[  0   1   8  27  64 125 216 343 512 729]
8
[ 8 27 64]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]
9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [71]:
"""
Multidimensional arrays can have one index per axis. 
These indices are given in a tuple separated by commas:
"""
def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4), dtype=int)
print(b)
print(b[1,3])
print(b[0:5, 1]) ## each row in the second column of b
print(b[:,1]) ## equivalent to the previous example
print()
print(b[1:3,:])# each column in the second and third row of b

#When fewer indices are provided than the number of axes, the missing 
#indices are considered complete slices:
print()
print(b[-1])## the last row. Equivalent to b[-1,:]


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
13
[ 1 11 21 31 41]
[ 1 11 21 31 41]

[[10 11 12 13]
 [20 21 22 23]]

[40 41 42 43]


In [72]:
"""
The expression within brackets in b[i] is treated as an i followed by as many instances of :
as needed to represent the remaining axes. NumPy also allows you to write this using dots 
as b[i,...].

NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For 
example, if x is an array with 5 axes, then

x[1,2,...] is equivalent to x[1,2,:,:,:],

x[...,3] to x[:,:,:,:,3] and

x[4,...,5,:] to x[4,:,:,5,:].
"""

c = np.array( [[[  0,  1,  2],# a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               
               [[100,101,102],
                [110,112,113]]])
print(c.shape)
print(c[1,...])# same as c[1,:,:] or c[1]
print(c[...,2]) # same as c[:,:,2]


(2, 2, 3)
[[100 101 102]
 [110 112 113]]
[[  2  13]
 [102 113]]


In [73]:
#Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)
print()
#However, if one wants to perform an operation on each element in the array, one can 
#use the flat attribute which is an iterator over all the elements of the array:  

for element in b.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [81]:
#Shape Manipulation
"""
Changing the shape of an array.
An array has a shape given by the number of elements along each axis:
"""
a = np.floor(10*random_generator.random((3,4)))
print(a)
print(a.shape)
print()
#The shape of an array can be changed with various commands. 
#Note that the following three commands all return a modified array,
#but do not change the original array:

print(a.ravel())#returns the array, flattened
print(a.ravel().shape)
print()
print(a.reshape(6,2))#returns the array with a modified shape
print()
print(a.T)#returns the array transposed
print()
print(a.T.shape)
print(a.shape)

[[9. 7. 5. 2.]
 [1. 9. 5. 1.]
 [6. 7. 6. 9.]]
(3, 4)

[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]
(12,)

[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]
 [6. 7.]
 [6. 9.]]

[[9. 1. 6.]
 [7. 9. 7.]
 [5. 5. 6.]
 [2. 1. 9.]]

(4, 3)
(3, 4)


In [75]:
"""
Why Numpy ? 
Ans: Numpy is faster compared to lists
1. Numpy array have int data type that is specified
for e.g : int16 int8 etc ,basically dtype
2. Lists have their own object value, object type, 
reference count and size, That roughly makes the objects 
of lists large/ More bytes of memory as everything is in binary .
3. Reading data from numpy array is quicker in that aspect.
4. No type checking when iterating through numpy array, makes it
faster. Lists have type checking as they may have all datatype obj
within the list
5. Numpy uses Contiguous memory. Meaning :
ALl the objects of numpy array are stored in memory side by side 
next to eachother.
List objects are stored in different locations of memory.Objects with 
pointer to next object value is stored within the memory cells.
"""

'\nWhy Numpy ? \nAns: Numpy is faster compared to lists\n1. Numpy array have int data type that is specified\nfor e.g : int16 int8 etc ,basically dtype\n2. Lists have their own object value, object type, \nreference count and size, That roughly makes the objects \nof lists large/ More bytes of memory as everything is in binary .\n3. Reading data from numpy array is quicker in that aspect.\n4. No type checking when iterating through numpy array, makes it\nfaster. Lists have type checking as they may have all datatype obj\nwithin the list\n5. Numpy uses Contiguous memory. Meaning :\nALl the objects of numpy array are stored in memory side by side \nnext to eachother.\nList objects are stored in different locations of memory.Objects with \npointer to next object value is stored within the memory cells.\n'

In [109]:
a = np.array([[9.,7.,5.,2.],[1.,9.,5.,1.],[6.,7.,6.,9.]],dtype='float32')
print(a)
a.resize((2,6))#size where product = no of elements
print()
print(a)

[[9. 7. 5. 2.]
 [1. 9. 5. 1.]
 [6. 7. 6. 9.]]

[[9. 7. 5. 2. 1. 9.]
 [5. 1. 6. 7. 6. 9.]]


Ravel : returns the array Flattened,
Reshape : returns the array reshaped based on the tuple .
Transpose : Returns Transpose of the array/Matrix

They do not change the array itself

Mechanism: 
The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as “C-style”.NumPy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied.


Resize: Numpy resize function resizes the array itself.

In [110]:
print(a)
a.resize((6,2))
print(a)
a.resize((1,12))
print(a)
a.ravel()
print(a)

[[9. 7. 5. 2. 1. 9.]
 [5. 1. 6. 7. 6. 9.]]
[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]
 [6. 7.]
 [6. 9.]]
[[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]]
[[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]]


In [122]:
#If a dimension is given as -1 in a reshaping operation, 
#the other dimensions are automatically calculated:
a = np.array([[9.,7.,5.,2.],[1.,9.,5.,1.],[6.,7.,6.,9.]],dtype='float32')
print(a.reshape(2,-1))
print()
print(a.reshape(1,-1))
print()
print(a.reshape(-1))
print()
print(a.reshape(6,-1))


[[9. 7. 5. 2. 1. 9.]
 [5. 1. 6. 7. 6. 9.]]

[[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]]

[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]

[[9. 7.]
 [5. 2.]
 [1. 9.]
 [5. 1.]
 [6. 7.]
 [6. 9.]]


# See Also : 
###### ndarray.shape, reshape, resize, ravel

### Stacking together different arrays
###### Vstack Hstack column_stack
###### Several arrays can be stacked together along different axes

In [149]:
a = np.floor(10*random_generator.random((2,2)))
print(a)
b = np.floor(10*random_generator.random((2,2)))
print(b)
print()
#Horizontal stack
print(np.hstack((a,b)))
print()
#Vertical stack
print(np.vstack((a,b)))

#Column Stack :
#The function column_stack stacks 1D arrays as columns into a 2D array.
#It is equivalent to hstack only for 2D arrays:

from numpy import newaxis
columnStack = np.column_stack((a,b))# With 2D arrays
print("Column Stack")
print(columnStack)
a = np.array([4.,2.])
b = np.array([5.,6.])
print("a -1D array")
print(a)
print("b -1D array")
print(b)
print()
oneD_Column_Stack = np.column_stack((a,b))#Column stack for 1D array
print("1D Column Stack")
print(oneD_Column_Stack)
print()
H_stack_oneD = np.hstack((a,b))
print("1D Horizontal Stack")
print(H_stack_oneD)
print()
#column vector
print("Visualize 1D array as column vectors")
print(a[:,newaxis])#View a as a column vector
print(b[:,newaxis])
print()
print("Column stack column vectors :")
print(np.column_stack((a[:,newaxis],b[:,newaxis])))
print()
print("Horizontal Stack Column Vectors :")
print(np.hstack((a[:,newaxis],b[:,newaxis])))

[[1. 7.]
 [2. 1.]]
[[0. 1.]
 [1. 5.]]

[[1. 7. 0. 1.]
 [2. 1. 1. 5.]]

[[1. 7.]
 [2. 1.]
 [0. 1.]
 [1. 5.]]
Column Stack
[[1. 7. 0. 1.]
 [2. 1. 1. 5.]]
a -1D array
[4. 2.]
b -1D array
[5. 6.]

1D Column Stack
[[4. 5.]
 [2. 6.]]

1D Horizontal Stack
[4. 2. 5. 6.]

Visualize 1D array as column vectors
[[4.]
 [2.]]
[[5.]
 [6.]]

Column stack column vectors :
[[4. 5.]
 [2. 6.]]

Horizontal Stack Column Vectors :
[[4. 5.]
 [2. 6.]]


#### the function row_stack is equivalent to vstack for any input arrays.

####  In fact, row_stack is an alias for vstack:

In [150]:
np.column_stack is np.hstack

False

In [151]:
np.row_stack is np.vstack

True